export const CREATE_NEW_ORDER_REQUEST = "CREATE_NEW_ORDER_REQUEST";
export const CREATE_NEW_ORDER_SUCCESS = "CREATE_NEW_ORDER_REQUEST";
export const CREATE_NEW_ORDER_FAIL = "CREATE_NEW_ORDER_REQUEST";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
