// Admin Section
export const ADMIN_ORDERS_REQUEST = "ADMIN_ORDERS_REQUEST";
export const ADMIN_ORDERS_SUCCESS = "ADMIN_ORDERS_SUCCESS";
export const ADMIN_ORDERS_FAIL = "ADMIN_ORDERS_FAIL";

export const UPDATE_ORDERS_REQUEST = "UPDATE_ORDERS_REQUEST";
export const UPDATE_ORDERS_SUCCESS = "UPDATE_ORDERS_SUCCESS";
export const UPDATE_ORDERS_RESET = "UPDATE_ORDERS_RESET";
export const UPDATE_ORDERS_FAIL = "UPDATE_ORDERS_FAIL";

export const DELETE_ORDERS_REQUEST = "DELETE_ORDERS_REQUEST";
export const DELETE_ORDERS_SUCCESS = "DELETE_ORDERS_SUCCESS";
export const DELETE_ORDERS_RESET = "DELETE_ORDERS_RESET";
export const DELETE_ORDERS_FAIL = "DELETE_ORDERS_FAIL";

// User Section
export const CREATE_NEW_ORDER_REQUEST = "CREATE_NEW_ORDER_REQUEST";
export const CREATE_NEW_ORDER_SUCCESS = "CREATE_NEW_ORDER_REQUEST";
export const CREATE_NEW_ORDER_FAIL = "CREATE_NEW_ORDER_REQUEST";

export const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST";
export const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS";
export const MY_ORDERS_FAIL = "MY_ORDERS_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAIL_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAIL_FAIL";

export const UPDATE_PAYMENT_REQUEST = "UPDATE_PAYMENT_REQUEST";
export const UPDATE_PAYMENT_SUCCESS = "UPDATE_PAYMENT_SUCCESS";
export const UPDATE_PAYMENT_RESET = "UPDATE_PAYMENT_RESET";
export const UPDATE_PAYMENT_FAIL = "UPDATE_PAYMENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
